### ISSUE TITLE
Is this platform dead for Storybook?

### ISSUE THREAD

**Issue by midzdotdev** [storybookjs/solidjs#3]
I tried a few months back to get my SolidStart project working with the latest storybook to no avail.

I tried, I really did, but I eventually gave up.

Seeing that this repo hasn't been updated in ~7 months, it begs the question if Storybook actually cares about providing first-party support for Solid.

There's also PR #2 from a poor guy who hasn't had a response in ~4 months.

_P.S. For others reading, I've looked for alternatives to SB, all I've found really is preview.js which is a bit temporamental._

**Comment by Regbit** [comment]
I too would like to see this developed. Maybe there an estimate timeframe or a condition for when the project can be worked on?

**Comment by JReinhold** [comment]
> it begs the question if Storybook actually cares about providing first-party support for Solid

This SolidJS integration is built and maintained by the community (@webblocksapp actually) and not part of Storybook core. We've included it as an automated framework with `npx storybook init` because we think it's good enough for most SolidJS use cases.

At the moment we don't have the resources within Storybook core to maintain this.

> I tried, I really did, but I eventually gave up.

If you experience actual issues or bugs I suggest you open issues detailing them. Based on the readme it seems there's still a handful of known features this integration does not support yet.

**Comment by JonahPlusPlus** [comment]
It's back with #10
